2023-04-03 14:54:20,507 - uvicorn.error - INFO - serve:75 - Started server process [900]
2023-04-03 14:54:20,508 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 14:54:20,510 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 14:54:35,580 - uvicorn.access - INFO - send:480 - 127.0.0.1:12852 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 14:54:35,809 - uvicorn.access - INFO - send:480 - 127.0.0.1:12852 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 14:58:35,902 - uvicorn.error - INFO - serve:75 - Started server process [12696]
2023-04-03 14:58:35,904 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 14:58:35,906 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 14:58:57,944 - uvicorn.access - INFO - send:480 - 127.0.0.1:12944 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 14:58:58,445 - uvicorn.access - INFO - send:480 - 127.0.0.1:12944 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 15:00:14,274 - uvicorn.error - INFO - serve:75 - Started server process [12116]
2023-04-03 15:00:14,320 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 15:00:14,332 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 15:00:20,152 - uvicorn.access - INFO - send:480 - 127.0.0.1:12967 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 15:00:22,041 - uvicorn.access - INFO - send:480 - 127.0.0.1:12967 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 15:02:46,029 - uvicorn.error - INFO - serve:75 - Started server process [2592]
2023-04-03 15:02:46,111 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 15:02:46,153 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 15:15:55,826 - uvicorn.error - INFO - shutdown:255 - Shutting down
2023-04-03 15:15:55,936 - uvicorn.error - INFO - shutdown:66 - Waiting for application shutdown.
2023-04-03 15:15:55,939 - uvicorn.error - INFO - shutdown:77 - Application shutdown complete.
2023-04-03 15:15:55,940 - uvicorn.error - INFO - serve:85 - Finished server process [2592]
2023-04-03 16:02:12,843 - uvicorn.error - INFO - serve:75 - Started server process [1512]
2023-04-03 16:02:12,850 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:02:12,856 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:02:16,798 - uvicorn.access - INFO - send:480 - 127.0.0.1:13836 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:02:16,813 - uvicorn.access - INFO - send:480 - 127.0.0.1:13836 - "POST /api/v1/ HTTP/1.1" 500
2023-04-03 16:02:16,815 - uvicorn.error - ERROR - run_asgi:412 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Programming\Workbooks\01. Kazee\iam-caption-api-nlp\.\app\api\router.py", line 15, in NLPRouteMain
    result = nlp.get_prediction(username, list_content)
  File "D:\Programming\Workbooks\01. Kazee\iam-caption-api-nlp\.\app\api\api_v1\endpoints\indobert_endpoint.py", line 19, in get_prediction
    logger.error('Error analysing a text :', e, "Username:", username)
UnboundLocalError: local variable 'e' referenced before assignment
2023-04-03 16:03:47,997 - uvicorn.error - INFO - serve:75 - Started server process [15376]
2023-04-03 16:03:47,999 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:03:48,007 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:04:29,565 - uvicorn.access - INFO - send:480 - 127.0.0.1:13897 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:04:29,772 - uvicorn.access - INFO - send:480 - 127.0.0.1:13897 - "POST /api/v1/ HTTP/1.1" 500
2023-04-03 16:04:29,781 - uvicorn.error - ERROR - run_asgi:412 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Programming\Workbooks\01. Kazee\iam-caption-api-nlp\.\app\api\router.py", line 15, in NLPRouteMain
    result = nlp.get_prediction(username, list_content)
  File "D:\Programming\Workbooks\01. Kazee\iam-caption-api-nlp\.\app\api\api_v1\endpoints\indobert_endpoint.py", line 21, in get_prediction
    output.update({"error-status": 1, "error-message": f"Error analysing a text: {e}. Make sure the list_content parameter has this format: [\"text1\", \"text2\", \"text3\", ...]. Double quotes is a necessity."})
UnboundLocalError: local variable 'e' referenced before assignment
2023-04-03 16:05:06,051 - uvicorn.error - INFO - serve:75 - Started server process [12932]
2023-04-03 16:05:06,053 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:05:06,055 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:05:16,272 - uvicorn.access - INFO - send:480 - 127.0.0.1:13911 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:05:16,501 - uvicorn.access - INFO - send:480 - 127.0.0.1:13911 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 16:06:07,844 - uvicorn.error - INFO - serve:75 - Started server process [9228]
2023-04-03 16:06:07,849 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:06:07,859 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:06:13,312 - uvicorn.access - INFO - send:480 - 127.0.0.1:13934 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:06:13,565 - uvicorn.access - INFO - send:480 - 127.0.0.1:13934 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 16:08:03,611 - uvicorn.error - INFO - serve:75 - Started server process [1172]
2023-04-03 16:08:03,612 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:08:03,616 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:08:39,147 - uvicorn.access - INFO - send:480 - 127.0.0.1:13975 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:08:39,705 - uvicorn.access - INFO - send:480 - 127.0.0.1:13975 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 16:11:33,796 - uvicorn.error - INFO - serve:75 - Started server process [9080]
2023-04-03 16:11:33,800 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:11:33,805 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:11:37,684 - uvicorn.access - INFO - send:480 - 127.0.0.1:14003 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:11:37,866 - uvicorn.access - INFO - send:480 - 127.0.0.1:14003 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 16:12:22,919 - uvicorn.error - INFO - serve:75 - Started server process [13840]
2023-04-03 16:12:22,924 - uvicorn.error - INFO - startup:47 - Waiting for application startup.
2023-04-03 16:12:22,927 - uvicorn.error - INFO - startup:61 - Application startup complete.
2023-04-03 16:12:26,978 - uvicorn.access - INFO - send:480 - 127.0.0.1:14014 - "POST /api/v1 HTTP/1.1" 307
2023-04-03 16:12:27,318 - uvicorn.access - INFO - send:480 - 127.0.0.1:14014 - "POST /api/v1/ HTTP/1.1" 200
2023-04-03 16:12:52,114 - uvicorn.error - INFO - shutdown:255 - Shutting down
